### DISCUSSION TITLE
Defining multiple types in schema (x OR type y)?

### DISCUSSION THREAD

**Discussion by DVAlexHiggs** [crdoconnor/strictyaml#181] [Q&A] [answered]
I have a YAML schema. I would like to allow a key in a Mapping to either have a List of Strings or just a String.

Something like:

```python
Map(
    {"my_keys": 
        Map({"my_key_1": Str() | Seq(Str()),
             "my_key_2": Str()})
})
```

Which would validate the following YAML, either:

```yaml
my_keys:
    my_key_1: "my_string"
    my_key_2: "my_other_string"
```

OR

```yaml
my_keys:
    my_key_1: 
       - "my_string"
       - "my_second_string"
    my_key_2: "my_other_string"
```

How do I do this with StrictYAML? I could not find anything in the docs. Thanks!
