### DISCUSSION TITLE
schema - how to limit Seq size?

### DISCUSSION THREAD

**Discussion by goyalyashpal** [crdoconnor/strictyaml#207] [Q&A]
hi! thanks for such wonderful writeups and this tool.

i wanted to design a quiz, so, thought to _eventually_ use strict-yaml for storing that data. it looks like this:

```yaml
- ques: What is name of default python implementation?
  correct: cpython
  choices: 4
  options:
    - cython
    - python
    - c++

- ques: What is name of contiguously indexed data-type in Python?
  correct: list
  choices: 4
  options:
    - array
    - queue
    - set
```

the python src containing the schema looks like:

```python
import strictyaml as sml


def main():
	data_schema = sml.Seq(
		sml.Map({
			"ques": sml.Str(),
			"correct": sml.Str(),
			"choices": sml.Int(),
			"options": sml.Seq(sml.Str()),
		})
	)

	path: str = \
	 "../inventory/datafile.yaml"

	with open(path, "r", encoding="utf-8") as file:
		raw_data: str = file.buffer.read().decode()
		data = sml.load(raw_data, data_schema).data
		print(data[1])


if __name__ == "__main__":
	main()
```

I was thinking if i could:
* specify the range of `choices` to be between `2` to `4`
* specify the length of `"options"` to be equal to `choices - 1`
or if not dynamically possible, then at least some static hard coded value?

Or otherwise, how would you deal with it? which markup language would seem fit for storing trivia quizes like this according to you?

I tried looking around at submenus of https://hitchdev.com/strictyaml/ , but couldn't find some reference focussing on the schema.
