### ISSUE TITLE
Recursive Schema

### ISSUE THREAD

**Issue by AdrianVollmer** [crdoconnor/strictyaml#126]
Hi,

is there a way to recursively define a schema or would this be a new feature? Does this even make sense?

Here is an example document that hopefully shows what I mean:

```
Section:
  Text: Short Introduction ...
  Subsections:
    - Section:
      -Text: Intro for first sub section ...
       Subsections:
         - Section:
              Text: Body of first sub sub section ...
         - Section:
              Text: Body of second sub sub section ...
```

So a section is a dictionary which contains a key named "Subsections" which is an empty list or a list of sections.
