### ISSUE TITLE
1.3.0 possibly breaking? when expecting a url found non-matching string

### ISSUE THREAD

**Issue by honzajavorek** [crdoconnor/strictyaml#134]
Hi, it seems with upgrading to 1.3.0 all my code where I use `strictyaml.Url()` stopped working. So far I only rolled back the upgrade I got through the Dependabot, but looking at the changelog, it seems like it might be something with the change in regular expressions?

I didn't have time yet to compile a nice minimal example to reproduce the issue, but suddenly get errors like

```
    raise YAMLValidationError(
strictyaml.exceptions.YAMLValidationError: when expecting a url
found non-matching string
  in "<unicode string>", line 13, column 1:
      link: https://medium.com/@honz ... 
    ^ (line: 13
```

on code like

```yaml
- title: dev.to
  lang: en
  link: https://dev.to/honzajavorek
  href: https://dev.to/feed/honzajavorek

- title: zdrojak.cz
  lang: cs
  link: https://www.zdrojak.cz/autori/honza-javorek/
  href: https://www.zdrojak.cz/autori/honza-javorek/feed/

- title: medium.com
  lang: en
  link: https://medium.com/@honzajavorek
  href: https://medium.com/feed/@honzajavorek
```

with schema

```python
import strictyaml as yaml

SCHEMA = yaml.Seq(
    yaml.Map({
        'date': yaml.Datetime(),
        'title': yaml.Str(),
        'event': yaml.Str(),
        yaml.Optional('lang', default='cs'): yaml.Enum([
            'cs',
            'en',
        ]),
        yaml.Optional('type', default='talk'): yaml.Enum([
            'talk',
            'workshop',
            'interview',
            'text',
        ]),
        yaml.Optional('url'): yaml.Url(),
        yaml.Optional('resources_type', default='slides'): yaml.Enum([
            'slides',
            'text',
        ]),
        yaml.Optional('resources_url'): yaml.Url(),
    }),
)
```
