### ISSUE TITLE
FEATURE: schema from data

### ISSUE THREAD

**Issue by kshpytsya** [crdoconnor/strictyaml#16]
Provide a way to construct schema from data. This would make it possible to have schema stored as a yaml file. I have a specific use case for this in the project that I am currently developing. Roughly speaking, there are several tiers of configurability, the first being the data and the second, among the other things, is the schema for that data. Currently I am using [Cerberus](http://docs.python-cerberus.org/en/stable/) for that purpose but since I intend to use `strictyaml` anyway, it feels a bit awkward to have two validators in the codebase.
Of course, I could build this functionality atop of `strictyaml` myself, but then I would need to both keep it in sync with `stricyaml` (should any new validators be added in the future) and write the end user documentation on "schema schema" whereas with `Cerberus` I can rely on existing documentation and just refer end-user to it.

**Comment by crdoconnor** [comment]
I'm not sure about this one. You can already read unstructured, schemaless data using strictyaml and you can also create partial schemas. You can ratchet up the strictness incrementally rather than generating a great big schema (which will likely change).

I'm also pretty averse to writing code generation tools (I've seen them go wrong too many times).

I'm intending on allowing the use of kwalify schemas at some point, but since these don't work for more complex schemas, it would be alongside the existing pythonic schema language.

**Comment by kshpytsya** [comment]
Correct me if I am mistaken, but I see at as very straightforward recursive constructor for validators with uniform direct correspondence to existing python validator classes and their parameters.
This would be trivial to implement but would be a pain to keep up-to-date if not being part of the `strictyaml` itself. I suspect that creative (isn't it always?) use of decorators on Validator classes could make this simple and elegant.

I don't quite get your remark on "code generation tools".

**Comment by crdoconnor** [comment]
Are you suggesting something like this::

    x:
      a: 1
      b: 2

    strictyaml.generate_schema(yaml_string) == """Map({"a": Int(), "b": Int()})"""

**Comment by kshpytsya** [comment]
No. Rather:

```
Map({
    "u": Seq(Bool),
    "x": Int(),
    "y": Enum(["a", "b", "c"]),
    "z": MapPattern(Int(), Str())
})
```

should be described as:

```
type: Map
validator:
    - u:
        type: Seq
        validator:
            type: Bool
    - x:
        type: Int
    - y:
        type: Enum
        restricted_to:
              - a
              - b
              - c
    - z:
        type: MapPattern
        key_validator:
            type: Int
        value_validator:
            type: Str
```

The values in "type" can be any of the leaf Validator classes (I am not sure if all classes in the `validators` module are meant to be usable by the user, or rather some are meant as base classes only). The rest of the keys should correspond to constructor arguments. 
Just as I said earlier, I believe that something like that can be elegantly implementing by some decorators decorating `Validator` subclasses.
