### ISSUE TITLE
A valid use case for flow style

### ISSUE THREAD

**Issue by leni536** [crdoconnor/strictyaml#20]
Maybe I shouldn't use strictyaml for linear algebra heavy stuff.

```yaml
matrix: [
  [ 2., 5., 1.],
  [ 3., 2., 3.],
  [ 4., 1., 2.],
  ]
matrix_strict:
  -
    - 2.
    - 5.
    - 1.
  -
    - 3.
    - 2.
    - 3.
  -
    - 4.
    - 1.
    - 2.
```
