### ISSUE TITLE
Indent should be consistent

### ISSUE THREAD

**Issue by guyskk** [crdoconnor/strictyaml#23]
* Feature request

How many indent spaces should I use?

I encounter many YAML files, some indent 4 spaces, some indent 2 spaces, 
and some indent 2 spaces before `- list`, and others not. 
Sometimes I got confused when they mixed:

```yaml
example:
  indent: 2 spaces
  items:
  - one
  - two
  others:
    - three
    - four
  inner:
      indent: 4 spaces
      items:
      - five
      - six
      others:
          - seven
          - eight
```
