### ISSUE TITLE
more critiques of toml

### ISSUE THREAD

**Issue by nhooyr** [crdoconnor/strictyaml#3]
First, TOML has quirky syntax for arrays of tables. It's not obvious that adding a second pair of brackets around the table will turn it into an array. Then if you have a nested table inside a table in a table of arrays, then it becomes even more unclear.

``` toml
# not clear that this is an array
[[tables]]
foo = "foo"

# especially now, it isn't clear at all that tables is actually an array
# and we are referencing the inner table of the last table added to the tables array.
[tables.inner]
foo = "bar"
```

Second, all arrays have the type `array`. So even though arrays are homogenous in TOML, you can oddly do 

``` toml
array = [["foo"], [1]]

# but not
array = ["foo", 1]
```

Which is very inconsistent.

Third, there is also inline table syntax which is the TOML equivalent of YAML's flow style. Same downsides.
