### ISSUE TITLE
Documentation not rendering 'given' sections

### ISSUE THREAD

**Issue by NoahTheDuke** [crdoconnor/strictyaml#32]
The documentation doesn't correctly display most `given:` code snippets, rendering the generated docs mostly unusable:

[Parsing comma separated items](https://github.com/crdoconnor/strictyaml/blob/94cd6baf3fead30ec6f002ead5c0d6d7c4dfa681/hitch/commaseparated.story#L18) shows:

```yaml
variations:
        Parse as int:
          given:
            yaml_snippet: |
              a: 1, 2, 3
          steps:
          - Run:
              code: |
                Ensure(load(yaml_snippet, int_schema)).equals({"a": [1, 2, 3]})
```

but the HTML rendered page doesn't display the `given:` snippet: [screenshot](https://i.imgur.com/aIeeY9S.png). This is consistent across all of the generated docs.
