### ISSUE TITLE
Support question: OpenAPI 3.0.x flow mapping workarounds

### ISSUE THREAD

**Issue by numberoverzero** [crdoconnor/strictyaml#38]
Thanks for the great library!  I'm hoping to use this instead of pyyaml when parsing [OpenAPI 3.0.x](https://github.com/OAI/OpenAPI-Specification/blob/1b9bb2e0464514d237536531ad518f4fa4e6f3a1/versions/3.0.0.md) documents, but I'm running into an issue with the [Security Requirements Object](https://github.com/OAI/OpenAPI-Specification/blob/1b9bb2e0464514d237536531ad518f4fa4e6f3a1/versions/3.0.0.md#securityRequirementObject) of a path item.

From that link, emphasis mine:
> Each name MUST correspond to a security scheme which is declared in the Security Schemes under the Components Object. If the security scheme is of type "oauth2" or "openIdConnect", then the value is a list of scope names required for the execution. **For other security scheme types, the array MUST be empty.**

This means I've got paths like this:

```
paths:
  /users/{userId}/widgets/{widgetId}/revisions:
    post:
      operationId: createWidgetRevision
      security:
        - apiToken: []
```

Which fails as expected with `FLowMappingDisallowed`:

```
$ ipython
Python 3.6.5 (default, Apr  1 2018, 15:30:28) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from strictyaml import load

In [2]: doc="""paths:
   ...:   /users/{userId}/widgets/{widgetId}/revisions:
   ...:     post:
   ...:       operationId: createWidgetRevision
   ...:       security:
   ...:         - apiToken: []"""

In [3]: load(doc)
FlowMappingDisallowed [traceback clipped]
```

Any recommendations?  There's also a commonly-used form for an unauthenticated method with a similar issue:

```
paths:
  /items/{itemId}:
    put:
      operationId: updateItem
      security:
        - {}
```

**Comment by crdoconnor** [comment]
Hi @numberoverzero thanks for your issue. I'm really sorry I haven't gotten back to you sooner. I was on holiday for the last couple of weeks (and with only intermittent internet access). I won't be so unresponsive from now on.

As to your question, I see two ways of dealing with it. Either make your YAML like this:

```
paths:
  /users/{userId}/widgets/{widgetId}/revisions:
    post:
      operationId: createWidgetRevision
      security:
        - apiToken: 
```

Using the EmptyList validator you could interpret the blank value as an empty list.

Or like this:

```
paths:
  /users/{userId}/widgets/{widgetId}/revisions:
    post:
      operationId: createWidgetRevision
      security:
        - apiToken: '[]'
```

Using Enum("[]") | SomeOtherValidator you could ensure that it is only possible to parse a string of '[]'.

Unfortunately I don't see another happy way of dealing with this problem without 1) enabling flow style or 2) adding this as some sort of special case where flow style is allowed, but only for empty strings.
