### ISSUE TITLE
Implicit default value for optional key in mappings?

### ISSUE THREAD

**Issue by fkromer** [crdoconnor/strictyaml#45]
According to the [optional keys docs](https://hitchdev.com/strictyaml/using/alpha/compound/optional-keys/) and the sources there is no support for an implicit default value for an optional key. My use case: I potentially have to configure a very long list of key value mappings for my command line application. The majority of the `optional-key`s usually have a default value which is implicit but from application/user perspective reasonable, not surprising. I know implicit data may be bad. Anyway... what do you think?

```
- mandatory-key: ...
  optional-key:
- mandatory-key: ...
  optional-key:
(... potentially very long list of other mappings ...)
```
