### ISSUE TITLE
Support for nested maps?

### ISSUE THREAD

**Issue by fkromer** [crdoconnor/strictyaml#47]
Does strictyaml support nested maps like this one? Is # nesting restricted?

```
a_nested_map:
  key: value
  another_key: Another Value
  another_nested_map:
    hello: hello
```
