### ISSUE TITLE
Preserve order of keys on load and dump

### ISSUE THREAD

**Issue by shoogle** [crdoconnor/strictyaml#68]
Ordinary YAML [does not mandate any particular ordering of keys](https://yaml.org/spec/1.2/spec.html#id2765608). This means that when a user creates a YAML file, such as this:

```yaml
key1: First value
key2: Second value
key3: Third value
```

It is perfectly valid for a YAML dumper to spit out this:

```yaml
key2: Second value
key1: First value
key3: Third value
```

Not only does it make a large file more difficult to read and understand, it also creates a false diff:

```diff
+key2: Second value
 key1: First value
-key2: Second value
 key3: Third value
```

It is easy to see how this could obscure a genuine change. Also, if the file is under version control then it will increase the size of a code repository for no good reason.

Possibly the strictYAML parser preseves ordering (I don't know, I haven't tried it yet). However, my argument is that this should be more than just an implementation detail. I believe that this should be an *actual feature of the strictYAML specification*, either as a MUST or at least STRONGLY RECOMMENED, and brought to the attention of implementors with a suitable example and justification.

P.S. Thank you for inventing StrictYAML!
