### ISSUE TITLE
Accessing comments in code

### ISSUE THREAD

**Issue by shoogle** [crdoconnor/strictyaml#95]
I know that StrictYAML parses comments and includes them when writing to a new doc, but I wondered whether there is a way to access comments individually like you can values.

Take this example doc:

```yaml
# This is a comment

a: x # another comment
b: c

# This is yet another comment

c: d
```

Is it possible to get the text from the comment next to `a`? Something like `print(a.comment)`.
