### ISSUE TITLE
Support request: How to formulate a schema containing partially exclusive or without Or?

### ISSUE THREAD

**Issue by fkromer** [crdoconnor/strictyaml#99]
I've a config which is partially exclusive OR. It may be either like this

```
common:
- ...
variant_a:
- ...
variant_a_again:
- ...
```

or

```
common:
- ...
variant_b:
- ...
variant_b_again:
- ...
```

Using a schema like `schema = Map({"common": Seq(...), "variant_a": Seq(...), "variant_a_again": Seq(...)}) |  Map({"common": Seq(...), "variant_b": Seq(...), "variant_b_again": Seq(...)})` should work. However I get this error `strictyaml.exceptions.InvalidValidatorError: You tried to Or ('|') together 2 Map validators. Try using revalidation instead.` which prevents me from using it. To me it's not clear how to do revalidation here. How do I have to use revalidation in this case?

**Comment by crdoconnor** [comment]
It should be possible. I'll try to write some code that will do this in
about an hour or so.

**Comment by fkromer** [comment]
@crdoconnor It's not time critical cause I have a (super ugly) workaround. Thx a lot.

**Comment by chrisburr** [comment]
I've just stumbled upon this use case as well.

@crdoconnor Did you come up with a solution for this?

**Comment by crdoconnor** [comment]
Yes, sorry I didn't get around to writing it and I got distracted. I'll do
so today.

**Comment by crdoconnor** [comment]
It is possible wit .revalidate I think.

**Comment by fkromer** [comment]
@chrisburr I use 2 schemas with a nested try except. As I said... really ugly. But it works :smile:

**Comment by chrisburr** [comment]
Thanks @crdoconnor, it happens to us all 😆 (btw I'm loving `strictyaml`)

@fkromer Beautiful! 😉 Unfortunately mines a little messier as the map is the key of another map:

```yaml
first_thing:
    input:
        url: http://example.com  # Str()

second_thing:
    input:
        id: 1234  # Int()

third_thing:
    input:
        job: first_thing  # Str() corresponding to one of the other top-level keys
```

I can workaround it by setting `input` to be a `Map()`  and then looping over the keys to check which key exists so I can `revalidate` with the corresponding schema but it feels overly complicated.
